name: Notify Discord on Commit

on:
  push:
    branches:
      - dev  # Or the branch you want to monitor

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Check if there are commits
        id: check_commits
        run: |
          if [ "${{ github.event.head_commit }}" == "null" ]; then
            echo "No commits found. Skipping message to Discord."
            exit 0  # Exit early if no commits are present
          else
            echo "Commits found, proceeding with Discord notification."
          fi

      - name: Send commit to Discord
        if: success()  # Only run if previous step succeeds
        uses: peter-evans/discord-webhook-action@v1
        with:
          url: https://discord.com/api/webhooks/1308011922184081418/zN7k6xMlXntKX15mQlDxbYKJbKqAJQzhFxFZ0UnhiBQY4pdAyhXTePhw4gTculChF9kp
          message: |
            **New Commit to Laravel-Geoprofs**
            - **Commit Message**: ${{ github.event.head_commit.message }}
            - **Author**: ${{ github.event.head_commit.author.name }}
            - **Commit URL**: [View Commit](${{ github.event.head_commit.url }})
