name: Notify Discord on Commit

on:
  push:
    branches:
      - dev  # Monitoring the 'dev' branch for changes

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check if there are commits
      - name: Check if there are commits
        id: check_commits
        run: |
          if [ "${{ github.event.head_commit }}" == "null" ]; then
            echo "No commits found. Skipping message to Discord."
            exit 0  # Exit early if no commits are present
          else
            echo "Commits found, proceeding with Discord notification."
          fi

      # Step 2: Debug commit information (to troubleshoot and check the values)
      - name: Debug commit data
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          echo "Commit author: ${{ github.event.head_commit.author.name }}"
          echo "Commit URL: ${{ github.event.head_commit.url }}"
          echo "Full Payload: ${{ toJson(github.event) }}"  # To see the entire payload

      # Step 3: Ensure commit message is not empty before sending to Discord
      - name: Send commit to Discord if message is valid
        if: ${{ success() && github.event.head_commit.message != '' }}
        uses: peter-evans/discord-webhook-action@v1  # Using the Discord webhook action
        with:
          url: https://discord.com/api/webhooks/1308011922184081418/zN7k6xMlXntKX15mQlDxbYKJbKqAJQzhFxFZ0UnhiBQY4pdAyhXTePhw4gTculChF9kp  # Your webhook URL
          message: |
            **New Commit to Laravel-Geoprofs (dev branch)**
            - **Commit Message**: ${{ github.event.head_commit.message }}
            - **Author**: ${{ github.event.head_commit.author.name }}
            - **Commit URL**: [View Commit](${{ github.event.head_commit.url }})
