
name: Notify Discord on Commit

on:
  push:
    branches:
      - Dev  # Or any other branch you want to monitor

jobs:
  send-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send commit to Discord
        uses: peter-evans/discord-webhook-action@v1
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            **New Commit to Laravel-Geopros**
            - Commit: ${{ github.event.head_commit.message }}
            - Author: ${{ github.event.head_commit.author.name }}
            - [View Commit](${{
              github.event.head_commit.url
            }})
